// <auto-generated />
using System;
using Dawn_Winery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dawn_Winery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240124173134_init6")]
    partial class init6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dawn_Winery.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Dawn_Winery.Models.EndProduct", b =>
                {
                    b.Property<string>("Mname")
                        .HasColumnType("text");

                    b.Property<int>("Aging")
                        .HasColumnType("integer");

                    b.Property<int>("Bottle")
                        .HasColumnType("integer");

                    b.Property<int>("Milil")
                        .HasColumnType("integer");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<bool>("Type")
                        .HasColumnType("boolean");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Mname");

                    b.ToTable("EndProduct");
                });

            modelBuilder.Entity("Dawn_Winery.Models.RawMaterial", b =>
                {
                    b.Property<string>("Hid")
                        .HasColumnType("text");

                    b.Property<int>("Acidity")
                        .HasColumnType("integer");

                    b.Property<int>("Alcohol")
                        .HasColumnType("integer");

                    b.Property<int>("Body")
                        .HasColumnType("integer");

                    b.Property<string>("Hname")
                        .HasColumnType("text");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<float>("Stock")
                        .HasColumnType("real");

                    b.Property<int>("Sweet")
                        .HasColumnType("integer");

                    b.Property<int>("Tannin")
                        .HasColumnType("integer");

                    b.Property<bool>("Type")
                        .HasColumnType("boolean");

                    b.HasKey("Hid");

                    b.ToTable("RawMaterial");
                });

            modelBuilder.Entity("Dawn_Winery.Models.Receipe", b =>
                {
                    b.Property<string>("Rname")
                        .HasColumnType("text");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<float>("G1Kilo")
                        .HasColumnType("real");

                    b.Property<float?>("G2Kilo")
                        .HasColumnType("real");

                    b.Property<float?>("G3Kilo")
                        .HasColumnType("real");

                    b.Property<float?>("G4Kilo")
                        .HasColumnType("real");

                    b.Property<float?>("G5Kilo")
                        .HasColumnType("real");

                    b.Property<float?>("G6Kilo")
                        .HasColumnType("real");

                    b.Property<string>("Grape1")
                        .HasColumnType("text");

                    b.Property<string>("Grape2")
                        .HasColumnType("text");

                    b.Property<string>("Grape3")
                        .HasColumnType("text");

                    b.Property<string>("Grape4")
                        .HasColumnType("text");

                    b.Property<string>("Grape5")
                        .HasColumnType("text");

                    b.Property<string>("Grape6")
                        .HasColumnType("text");

                    b.Property<int>("SO2")
                        .HasColumnType("integer");

                    b.Property<bool>("Type")
                        .HasColumnType("boolean");

                    b.HasKey("Rname");

                    b.ToTable("Receipe");
                });
#pragma warning restore 612, 618
        }
    }
}
